# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'klima.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

dereceSayi=24
class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(353, 340)
        mainWindow.setStyleSheet("#mainWindow{\n"
"    background-color: rgb(222, 252, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dereceLabel = QtWidgets.QLabel(self.centralwidget)
        self.dereceLabel.setEnabled(True)
        self.dereceLabel.setGeometry(QtCore.QRect(10, 0, 81, 91))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.dereceLabel.setFont(font)
        self.dereceLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dereceLabel.setStyleSheet("font-size:75px;")
        self.dereceLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dereceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dereceLabel.setWordWrap(False)
        self.dereceLabel.setObjectName("dereceLabel")
        self.powerButon = QtWidgets.QPushButton(self.centralwidget)
        self.powerButon.setEnabled(True)
        self.powerButon.setGeometry(QtCore.QRect(10, 150, 81, 61))
        self.powerButon.setStyleSheet("#powerButon{\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius: 20px;\n"
"}")
        self.powerButon.setText("")
        self.powerButon.setIconSize(QtCore.QSize(16, 16))
        self.powerButon.setObjectName("powerButon")
        self.modeButon = QtWidgets.QPushButton(self.centralwidget)
        self.modeButon.setGeometry(QtCore.QRect(260, 150, 81, 61))
        self.modeButon.setStyleSheet("#modeButon{\n"
"    background-color: rgb(90, 255, 250);\n"
"    background-color: rgb(255, 235, 162);\n"
"border-radius: 20px;\n"
"}")
        self.modeButon.setObjectName("modeButon")
        self.dereceButon1 = QtWidgets.QPushButton(self.centralwidget)
        self.dereceButon1.setGeometry(QtCore.QRect(130, 190, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.dereceButon1.setFont(font)
        self.dereceButon1.setStyleSheet("#dereceButon1{\n"
"font-size:30px;\n"
"    background-color: rgb(76, 253, 255);\n"
"border-radius: 20px;\n"
"}")
        self.dereceButon1.setObjectName("dereceButon1")
        self.dereceButon2 = QtWidgets.QPushButton(self.centralwidget)
        self.dereceButon2.setGeometry(QtCore.QRect(130, 270, 91, 41))
        self.dereceButon2.setStyleSheet("#dereceButon2{\n"
"font-size:30px;\n"
"background-color: rgb(76, 253, 255);\n"
"border-radius: 20px;\n"
"}")
        self.dereceButon2.setObjectName("dereceButon2")
        self.fanButon = QtWidgets.QPushButton(self.centralwidget)
        self.fanButon.setGeometry(QtCore.QRect(10, 290, 81, 41))
        self.fanButon.setStyleSheet("#fanButon{\n"
"    background-color: rgb(53, 255, 215);\n"
"border-radius: 20px;\n"
"}")
        self.fanButon.setObjectName("fanButon")
        self.turboButon = QtWidgets.QPushButton(self.centralwidget)
        self.turboButon.setGeometry(QtCore.QRect(260, 290, 81, 41))
        self.turboButon.setStyleSheet("#turboButon{\n"
"    background-color: rgb(53, 255, 215);\n"
"border-radius: 20px;\n"
"}")
        self.turboButon.setObjectName("turboButon")
        self.cutButon = QtWidgets.QPushButton(self.centralwidget)
        self.cutButon.setGeometry(QtCore.QRect(10, 230, 81, 41))
        self.cutButon.setStyleSheet("#cutButon{\n"
"    background-color: rgb(53, 255, 215);\n"
"border-radius: 20px;\n"
"}")
        self.cutButon.setObjectName("cutButon")
        self.modLabel = QtWidgets.QLabel(self.centralwidget)
        self.modLabel.setGeometry(QtCore.QRect(100, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.modLabel.setFont(font)
        self.modLabel.setStyleSheet("font-weight:bold;")
        self.modLabel.setObjectName("modLabel")
        self.fanLabel = QtWidgets.QLabel(self.centralwidget)
        self.fanLabel.setGeometry(QtCore.QRect(100, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fanLabel.setFont(font)
        self.fanLabel.setStyleSheet("font-weight:bold;")
        self.fanLabel.setObjectName("fanLabel")
        self.swingButon = QtWidgets.QPushButton(self.centralwidget)
        self.swingButon.setGeometry(QtCore.QRect(260, 230, 81, 41))
        self.swingButon.setStyleSheet("#swingButon{\n"
"    background-color: rgb(53, 255, 215);\n"
"border-radius: 20px;\n"
"}")
        self.swingButon.setObjectName("swingButon")
        self.swingLabel = QtWidgets.QLabel(self.centralwidget)
        self.swingLabel.setGeometry(QtCore.QRect(100, 70, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.swingLabel.setFont(font)
        self.swingLabel.setStyleSheet("font-weight:bold;")
        self.swingLabel.setObjectName("swingLabel")
        self.modLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.modLabel2.setGeometry(QtCore.QRect(150, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.modLabel2.setFont(font)
        self.modLabel2.setObjectName("modLabel2")
        self.fanLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.fanLabel2.setGeometry(QtCore.QRect(190, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fanLabel2.setFont(font)
        self.fanLabel2.setObjectName("fanLabel2")
        self.swingLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.swingLabel2.setGeometry(QtCore.QRect(260, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.swingLabel2.setFont(font)
        self.swingLabel2.setObjectName("swingLabel2")
        self.klimaLabel = QtWidgets.QLabel(self.centralwidget)
        self.klimaLabel.setGeometry(QtCore.QRect(10, 100, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.klimaLabel.setFont(font)
        self.klimaLabel.setStyleSheet("color:red;")
        self.klimaLabel.setText("")
        self.klimaLabel.setObjectName("klimaLabel")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Klima Kumandası"))
        self.dereceLabel.setText(_translate("mainWindow", "24"))
        self.modeButon.setText(_translate("mainWindow", "MODE"))
        self.dereceButon1.setText(_translate("mainWindow", "↑"))
        self.dereceButon2.setText(_translate("mainWindow", "↓"))
        self.fanButon.setText(_translate("mainWindow", "FAN"))
        self.turboButon.setText(_translate("mainWindow", "TURBO"))
        self.cutButon.setText(_translate("mainWindow", "SHORT CUT"))
        self.modLabel.setText(_translate("mainWindow", "MOD:"))
        self.fanLabel.setText(_translate("mainWindow", "FAN HIZI:"))
        self.swingButon.setText(_translate("mainWindow", "SWING"))
        self.swingLabel.setText(_translate("mainWindow", "KANAT HAREKETİ:"))
        self.modLabel2.setText(_translate("mainWindow", "SOĞUTMA"))
        self.fanLabel2.setText(_translate("mainWindow", "DÜŞÜK"))
        self.swingLabel2.setText(_translate("mainWindow", "HAREKETLİ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
